### ISSUE TITLE
list_rows does not return the full iterator

### ISSUE THREAD

**Issue by jakewilliami** [caplena/caplena-python#1]
It appears that pagination is broken for listing rows in the project:

```python3
>>> len(project.list_rows())
10
>>> project.list_rows().count
500
```

**Comment by nicohaenggi** [comment]
Thanks for raising this issue, we are aware of it and will be issuing a fix within the next few days. In the meantime, you can specify a large `limit` to circumvent the problem, e.g.

```
project.list_rows(limit=1000))
```

**Comment by jakewilliami** [comment]
Thank you @nicohaenggi.  Unfortunately I can’t be sure that I have fewer than 1000 rows in Caplena, but I look forward to the fix being pushed!
